name: filedrop
base: core22
version: "2.0.0"
summary: Simple drag-and-drop LAN file transfer
description: |
  …

grade: stable
confinement: strict
architectures: [amd64]

apps:
  filedrop:
    command: bin/FileDrop
    environment:
      HOME: $SNAP_REAL_HOME
    plugs:
      - network
      - network-bind
      - home
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - opengl

parts:
  filedrop:
    plugin: nil
    source: .
    build-packages:
      - python3
      - python3-pip
      - python3-venv
      - build-essential
      - patchelf
    stage-packages:
      - libgl1
    override-build: |
      python3 -m pip install --upgrade pip
      pip3 install -r requirements.txt
      pip3 install -r FileDrop_Web/requirements.txt
      pip3 install pyinstaller
      python3 FileDrop_Web/build_vendor.py
      pyinstaller -y --clean FileDrop.spec
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp -r dist/FileDrop/* $CRAFT_PART_INSTALL/bin/
