name: filedrop
base: core22
version: "2.0.0"
summary: Simple drag-and-drop LAN file transfer
description: |
  …

grade: stable
confinement: strict
architectures: [amd64]

apps:
  filedrop:
    command: bin/FileDrop
    desktop: snap/gui/filedrop.desktop
    environment:
      HOME: $SNAP_REAL_HOME
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/bin/_internal/PyQt5/Qt5/plugins/platforms
      QT_PLUGIN_PATH: $SNAP/bin/_internal/PyQt5/Qt5/plugins
    plugs:
      - network
      - network-bind
      - home
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - opengl

parts:
  filedrop:
    plugin: nil
    source: .
    build-packages:
      - python3
      - python3-pip
      - python3-venv
      - libpython3.10
      - python3.10-dev
      - build-essential
      - patchelf
    stage-packages:
      - libgl1
      - libx11-xcb1
      - libxcb1
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb-util1
      - libxcb-cursor0
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libxi6
      - libxrender1
      - libxdamage1
      - libxcomposite1
      - libxcursor1
      - libxtst6
      - libnss3
      - libglib2.0-0
      - libdbus-1-3
      - libfontconfig1
      - libfreetype6
      - libgcc-s1
      - libstdc++6
    override-build: |
      python3 -m pip install --upgrade pip
      pip3 install -r requirements.txt
      pip3 install -r FileDrop_Web/requirements.txt
      pip3 install pyinstaller
      python3 FileDrop_Web/build_vendor.py
      pyinstaller -y --clean FileDrop.spec
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp -r dist/FileDrop/* $CRAFT_PART_INSTALL/bin/
